frspageid: 7369361 # Page ID of the WP:FRS page
gaguidelinesheaderpageid: # Page ID of the page containing the GA guidelines header, that maps the topics to subtopics # Wikipedia:Good article nominations/guidelines header
sentcountpageid: 7443324 # Page ID of the page used to store the SentCount JSON
rfcsdonepageid: 7443321 # Page ID of the page used to store the RFCs done JSON
editlimit: # A number representing the limit on the number of edits the bot can have.
